# Generated by Django 4.2.4 on 2024-06-01 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.IntegerField()),
                ('details', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=150)),
                ('dateTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('probability', models.DecimalField(decimal_places=2, max_digits=5)),
                ('details', models.TextField(blank=True, null=True)),
                ('impact', models.DecimalField(decimal_places=2, max_digits=5)),
                ('events', models.ManyToManyField(blank=True, null=True, to='api.event')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('efficiency', models.DecimalField(decimal_places=2, max_digits=5)),
                ('details', models.TextField(blank=True, null=True)),
                ('events', models.ManyToManyField(blank=True, null=True, to='api.event')),
                ('risks', models.ManyToManyField(blank=True, null=True, to='api.risk')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('criticality', models.DecimalField(decimal_places=2, max_digits=5)),
                ('details', models.TextField(blank=True, null=True)),
                ('risk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.risk')),
            ],
        ),
        migrations.AddField(
            model_name='control',
            name='risks',
            field=models.ManyToManyField(to='api.risk'),
        ),
    ]
