# Generated by Django 4.2.4 on 2024-06-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event_risk_process_asset_control_risks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='efficiency',
        ),
        migrations.AlterField(
            model_name='control',
            name='risks',
            field=models.ManyToManyField(blank=True, null=True, related_name='controls', to='api.risk'),
        ),
        migrations.AlterField(
            model_name='process',
            name='risks',
            field=models.ManyToManyField(blank=True, null=True, related_name='processes', to='api.risk'),
        ),
    ]
